# Generated by Django 4.0.2 on 2022-02-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
