# Generated by Django 4.0.2 on 2022-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='rareapi.PostTag', to='rareapi.Tag'),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.URLField(default=None),
        ),
    ]
