# Generated by Django 4.0.2 on 2022-02-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_alter_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
