# Generated by Django 4.0.2 on 2022-02-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0006_rename_author_id_comment_author_and_more'),
        ('rareapi', '0007_rename_admin_id_demotionqueue_admin_and_more'),
    ]

    operations = [
    ]
